### ISSUE TITLE
Not python 3 friendly

### ISSUE THREAD

**Issue by lzamparo** [davek44/Basset#15]
Hi,

Love the package, I'm keen to try it out for myself.  Just wanted to point out that it doesn't seem to play well with Python 3.  Some errors are easily fixed by running 2to3 on the relevant .py files, but some are not.  For example, try running install_data.py using Anaconda Python 3.  I get the following:

```
[zamparol@gpu-1-14 Basset]$ python install_data.py -r
[edited for brevity]
Traceback (most recent call last):
  File "/cbio/cllab/nobackup/zamparol/Basset/src/seq_hdf5.py", line 130, in <module>
    main()
  File "/cbio/cllab/nobackup/zamparol/Basset/src/seq_hdf5.py", line 46, in main
    seqs, targets = dna_io.load_data_1hot(fasta_file, targets_file, extend_len=options.extend_length, mean_norm=False, whiten=False, permute=False, sort=False)
  File "/cbio/cllab/nobackup/zamparol/Basset/src/dna_io.py", line 293, in load_data_1hot
    seq_vecs = hash_sequences_1hot(fasta_file, extend_len)
  File "/cbio/cllab/nobackup/zamparol/Basset/src/dna_io.py", line 267, in hash_sequences_1hot
    seq_vecs[header] = dna_one_hot(seq, seq_len)
  File "/cbio/cllab/nobackup/zamparol/Basset/src/dna_io.py", line 137, in dna_one_hot
    seq = seq[seq_trim:seq_trim+seq_len]
TypeError: slice indices must be integers or None or have an __index__ method
```

The same script seems to succeed using Anaconda Python 2.7.1 (though I can't be sure, the seq_hdf5.py step takes a while to complete).  I'll use that for my purposes, but maybe you should update the readme to explicitly say python 2 is required?

**Comment by onceupon** [comment]
i met the same problem using the docker image, with Python 2.7.6

**Comment by CesarArenas-Mena** [comment]
I guess the error in  line 92 of current seq_hdf5.py while running python 2.7.5  is related 

```
[ca445@cbsugpu01 bassetfiles]$ python /usr/local/Basset-0.1.0/src/seq_hdf5.py -r -c -v 3000 -t 3000 learn_cd4.fa lt.txt learn_cd4.h5
85261 training sequences
3000 test sequences
3000 validation sequences
Traceback (most recent call last):
  File "/usr/local/Basset-0.1.0/src/seq_hdf5.py", line 130, in <module>
    main()
  File "/usr/local/Basset-0.1.0/src/seq_hdf5.py", line 92, in main
    train_seqs, train_targets = seqs[i:i+train_count,:], targets[i:i+train_count,:]
TypeError: slice indices must be integers or None or have an __index__ method

```
