### ISSUE TITLE
trouble with basset_motifs.py 

### ISSUE THREAD

**Issue by rschwess** [davek44/Basset#22]
Hi again, 

After happily finishing the training procedure and (model testing running fine) ... I am running into troubles with basset_motifs.py:

I basically get a couple of these error:

/home/ron/anaconda2/lib/python2.7/site-packages/weblogolib/logomath.py:114: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if  self._mean ==None:

Before the script stops working throwing (aftr 25 motif steps):

Traceback (most recent call last):
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 659, in <module>
    main()
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 125, in main
    filter_possum(filter_weights[f,:,:], 'filter%d'%f, '%s/filter%d_possum.txt'%(options.out_dir,f), options.trim_filters)
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 558, in filter_possum
    while np.max(param_matrix[:,trim_start]) - np.min(param_matrix[:,trim_start]) < trim_t:
IndexError: index 19 is out of bounds for axis 1 with size 19

My learned model files are still pretty small (68 MB before 129 MB after decuda ...) Not sure if that might be a problem or hint to a faulty training run ...

Cheers,
Ron

**Comment by davek44** [comment]
It looks like there's a bug in the trim code. I uploaded a new version of the script that should fix it.

**Comment by rschwess** [comment]
Looks better thanks!

Still worrying messages from the log:

Processing query 235 out of 235 
Estimating pi_0 from all 1468 observed p-values.
Estimating pi_0.
Estimated pi_0=1
/home/ron/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/data.py:167: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "
/home/ron/anaconda2/lib/python2.7/site-packages/sklearn/preprocessing/data.py:184: UserWarning: Numerical issues were encountered when scaling the data and might not be solved. The standard deviation of the data is probably very close to 0. 
  warnings.warn("Numerical issues were encountered "
basset_motifs_predict.lua dnase_with_prim_erythroid_cnn_best.decuda.th motifs_out/sample.h5 motifs_out/model_out.h5
Filter 0
Filter 1

##########################################

Filter 296
Filter 297
Filter 298
Filter 299
6 segments of length 97
6 segments of length 97
Traceback (most recent call last):
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 668, in <module>
    main()
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 192, in main
    plot_filter_seg_heat(filter_outs, '%s/filter_segs_raw.pdf'%options.out_dir, whiten=False)
  File "/home/ron/tools/Basset/src/basset_motifs.py", line 516, in plot_filter_seg_heat
    sns.clustermap(filter_seqs[:,seqs_i], metric=dist, row_cluster=True, col_cluster=True, linewidths=0, xticklabels=False, vmin=hmin, vmax=hmax)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 1169, in clustermap
    **kwargs)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 1008, in plot
    row_linkage=row_linkage, col_linkage=col_linkage)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 941, in plot_dendrograms
    axis=1, ax=self.ax_col_dendrogram, linkage=col_linkage)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 684, in dendrogram
    label=label, rotate=rotate)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 502, in __init__
    self.dendrogram = self.calculate_dendrogram()
  File "/home/ron/anaconda2/lib/python2.7/site-packages/seaborn/matrix.py", line 582, in calculate_dendrogram
    color_threshold=-np.inf)
  File "/home/ron/anaconda2/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 2230, in dendrogram
    is_valid_linkage(Z, throw=True, name='Z')
  File "/home/ron/anaconda2/lib/python2.7/site-packages/scipy/cluster/hierarchy.py", line 1412, in is_valid_linkage
    name_str)
ValueError: Linkage 'Z' contains negative indices.

################

**Comment by davek44** [comment]
I know I've seen that before, but I can't replicate it at the moment. I would guess that one of the filters isn't activating at all and causing the statistical code to choke. I never got much value out of those heat map plots, so I'm going to turn them off by default and keep my eye out for an opportunity to fix the bug next time that I see it.

**Comment by rschwess** [comment]
Sorry for the delay and thanks for the workaround, the same example now runs without complaints.
