### ISSUE TITLE
Error in running basset_sat_vcf.py

### ISSUE THREAD

**Issue by huruifeng** [davek44/Basset#44]
I am trying to run the basset_sat_vcf.py, but it returns errors:
Here is the cmd:
`software/Basset-master/src/basset_sat_vcf2.py -t 6 -o /sat model_default_1k/dnacnn_best.th Test_run/rs13336428.vcf`
 And errors:
```
/opt/torch/install/bin/lua: /opt/torch/install/share/lua/5.2/nn/Container.lua:67:
In 13 module of nn.Sequential:
/opt/torch/install/share/lua/5.2/torch/Tensor.lua:466: Wrong size for view. Input size: 4x200x1x13. Output size: 4x4200
stack traceback:
        [C]: in function 'error'
        /opt/torch/install/share/lua/5.2/torch/Tensor.lua:466: in function 'view'
        /opt/torch/install/share/lua/5.2/nn/Reshape.lua:46: in function </opt/torch/install/share/lua/5.2/nn/Reshape.lua:31>
        [C]: in function 'xpcall'
        /opt/torch/install/share/lua/5.2/nn/Container.lua:63: in function 'rethrowErrors'
        /opt/torch/install/share/lua/5.2/nn/Sequential.lua:44: in function </opt/torch/install/share/lua/5.2/nn/Sequential.lua:41>
        (...tail calls...)
        /opt/Basset/src/convnet.lua:509: in function 'predict'
        ...software/Basset-master/src/../src/basset_sat_predict.lua:75: in main chunk
        [C]: in function 'dofile'
        /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
        [C]: in function 'error'
        /opt/torch/install/share/lua/5.2/nn/Container.lua:67: in function 'rethrowErrors'
        /opt/torch/install/share/lua/5.2/nn/Sequential.lua:44: in function </opt/torch/install/share/lua/5.2/nn/Sequential.lua:41>
        (...tail calls...)
        /opt/Basset/src/convnet.lua:509: in function 'predict'
        ...software/Basset-master/src/../src/basset_sat_predict.lua:75: in main chunk
        [C]: in function 'dofile'
        /opt/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
        [C]: in ?
Traceback (most recent call last):
  File "/data/gpei/software/Basset-master/src/basset_sat_vcf2.py", line 206, in <module>
    main()
  File "/data/gpei/software/Basset-master/src/basset_sat_vcf2.py", line 88, in main
    hdf5_in = h5py.File(options.model_hdf5_file, 'r')
  File "/data/gpei/software/python2.7_module/h5py/_hl/files.py", line 312, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/data/gpei/software/python2.7_module/h5py/_hl/files.py", line 142, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 78, in h5py.h5f.open
IOError: Unable to open file (unable to open file: name = '/data/gpei/19_1.CNN/2.model_default_1k/4.sad/sat/model_out.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

```

Any one can help me ?
Thanks!

**Comment by davek44** [comment]
Hi, it's most likely the case that the sequence length that you're giving the model is different from what it was trained on. It looks like you used length 1000 from your directory name. So maybe try "-l 1000" to basset_sat_vcf.py.
